---
- name: run the playbook tasks on the localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
  
   - name: ensure have last hotballoon-shed master version
     git:
       repo: 'https://github.com/flexiooss/hotballoon-shed.git'
       dest: /home/hotballoon-shed
       version: master
